# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'BlobSPN'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: latestVersion
    pwsh: false
    Inline: |
      Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      Install-Module -Name Az.DesktopVirtualization -Force -Verbose -Scope CurrentUser
      Write-Host "##[debug] Pubishing AVD Msix Package:"
      Write-Host "##[debug] `tAVD Resource Group"
      Write-Host "##[debug] `tAVD Host Pool Name: "
      Write-Host "##[debug] `tMsix Application UNC Path:"
      Write-Host "##[debug] `tMsix Application UNC FileName:"
      Write-Host "##[debug] `tMsix App Attach image complete Path: "
      Write-Host "##[debug] `tApplication Display Name:"
     
